# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: All Resonance
subtitle: 夫君子之行，静以修身，俭以养德，非淡泊无以明志，非宁静无以致远～
keywords: Shilin的备忘录,html/css/JavaScript,前端工程师,Vue,React,Node.js
description: 夫君子之行，静以修身，俭以养德，非淡泊无以明志，非宁静无以致远～
author: all-resonance
language: zh-CN
timezone: ''
avatar: https://cdn.nlark.com/yuque/0/2022/png/1429353/1648780999326-avatar/e6a1ea94-d01e-4cfa-8b55-17e74afcb162.png?x-oss-process=image%2Fresize%2Cm_fill%2Cw_320%2Ch_320%2Fformat%2Cpng

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://resonance.fun
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
# tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: volantis

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://gitee.com/xiangshilin/blog.git
  branch: gh-pages
  name: 295755973@qq.com
  email: 295755973@qq.com

# 发布平台
links:
  segementfault: https://segmentfault.com/
  v2ex: https://www.v2ex.com/
  yunqi: https://yq.aliyun.com/
  cnode: http://cnodejs.org/
  cvue: https://www.vue-js.com/

jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true

marked:
  gfm: true
  breaks: false

favicon: images/favicon.ico